### ISSUE TITLE
Ask before recursively deleting

### ISSUE THREAD

**Issue by mindeavor** [onmodulus/demeteorizer#123]
Using the `-o` option I somehow deleted the parent folder and everything in it, which happened to include 9 other project folders. Not happy.

**Comment by mindeavor** [comment]
It also deleted the `.git` folders inside said projects, so I can't even `git reset` my sources back to local commits

**Comment by mindeavor** [comment]
Apparently this is a duplicate of an issue that happened **6 months ago** (https://github.com/onmodulus/demeteorizer/issues/86). Please be responsible and fix this issue ASAP.

**Comment by robertBrown** [comment]
Gilbert,

I'll look into the issue. We are currently adding more enhancements into
demeteorizer as well as new unit tests.

I apologize for the disruption.

Have a great day,
Bobby

On Sunday, April 12, 2015, Gilbert <notifications@github.com> wrote:

> Apparently this is a duplicate of an issue that happened *6 months ago* (
> #86 <https://github.com/onmodulus/demeteorizer/issues/86>). Please be
> responsible and fix this issue ASAP.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/onmodulus/demeteorizer/issues/123#issuecomment-92158396>
> .
>


-- 


- Robert Brown

**Comment by vqc** [comment]
yep, this happened to me just now as well. thanks guys.

**Comment by sjmcdowall** [comment]
I maybe able to help on this if we can come up with a decent design pattern.  I am thinking if the directory exists instead it tries to create a .demeteorizer folder in there.  If that folder (.demeteorizer) exists I think it's safe to think that it can be rm -rf.  Of course a warning message about changing the directory to .demeteorizer within the -o folder would be given.  

Still breaks backward compatibility -- but since the reason for doing this is to change that behavior it may be ok. 

We could also add a -force type option to still rm -rf the -o .. if -o given without -f just error out..

**Comment by fiveisprime** [comment]
I was thinking add a prompt for deleting the directory, but also add a command
line option to skip the prompt so that automated systems can be updated to work
the same.

**Comment by fiveisprime** [comment]
In the next version, the output directory will be overwritten (`bundle` will be
added) if present. No more recursive deletes!
