### ISSUE TITLE
modulus deploy fails with EPERM error, because of read-only files?

### ISSUE THREAD

**Issue by fabyeah** [onmodulus/demeteorizer#124]
<code>modulus deploy</code> fails with <code>Error: EPERM, operation not permitted</code> [...] <code>\testapp3\.demeteorized\star.json'</code>

Seems like demeteorizer generates read-only files, which can't be deleted on cleanup.

I need to manually delete .demeteorizer folder or unset folder's "read-only" property, before every deploy.

Windows 7, Meteor 1.1-rc.0, Modulus 3.5.0

**Comment by robertBrown** [comment]
Thanks for the heads up. I will be looking into this later today.



On Wednesday, April 15, 2015, fabyeah <notifications@github.com> wrote:

> modulus deploy fails with Error: EPERM, operation not permitted [...]
> \testapp3.demeteorized\star.json'
>
> Seems like demeteorizer generates read-only files, which can't be deleted
> on cleanup.
>
> I need to manually delete .demeteorizer folder or unset folder's
> "read-only" property, before every deploy.
>
> Windows 7, Meteor 1.1-rc.0, Modulus 3.5.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/onmodulus/demeteorizer/issues/124>.
>


-- 


- Robert Brown

**Comment by mave79** [comment]
After struggling with this issue for a long time - finally figured it out.

Turns out - on Windows - delteing a file requires read/write permission on the file - as opposed to just the folder in unix. This caused unlink - to fail.  

As of Node 12.4 - the nodejs was fixed to make the behavior consistent in windows and unix. So upgrading to node 12.4 - resolves this problem.

**Comment by vivekvrao** [comment]
After struggling with this issue for a long time - finally figured it out.

Turns out - on Windows - delteing a file requires read/write permission on the file - as opposed to just the folder in unix. This caused unlink - to fail.  

As of Node 12.4 - the nodejs was fixed to make the behavior consistent in windows and unix. So upgrading to node 12.4 - resolves this problem.

**Comment by fiveisprime** [comment]
@vivekvrao thanks a lot for following up on this. I'll add a note to the
readme. :+1:

**Comment by fabyeah** [comment]
:+1:  @vivekvrao I updated node and now it works like a charm. Thank you!
