### ISSUE TITLE
bcrypt 0.7.8 not compatible with the latest Node (0.12.6)

### ISSUE THREAD

**Issue by ruchevits** [onmodulus/demeteorizer#128]
Changing the following line in `.demeteorized/package.json`:

    "bcrypt": "https://registry.npmjs.org/bcrypt/-/bcrypt-0.7.8.tgz"

to use newer version of `bcrypt` fixes the issue:

    "bcrypt": "0.8.3"

https://www.npmjs.com/package/bcrypt#version-compatibility

**Comment by fiveisprime** [comment]
Is Meteor on 0.12 yet?

**Comment by ruchevits** [comment]
Works fine for me. `node-fibers` support for 0.12 was released a few days ago: https://github.com/laverdet/node-fibers/issues/203

**Comment by fiveisprime** [comment]
Right right, but demeteorizer honors the node version that Meteor specifies.
Right now, that is 0.10.36, which bcrypt@0.7.8 does work with.

This is a non-issue because the converted application is meant to run on
node@0.10.36 (check the `engines` property of the generated package.json) along
with dependencies at the version specified by Meteor.

If you are planning to run the converted application, you'll have to stick with
the version of node that's specified in the package.json `engines` field or
manually change dependencies after converting.

You can use something like [nvm](https://github.com/creationix/nvm) or [nave](https://www.npmjs.com/package/nave) to manage local node versions. That
may help ease your pain. :)
