### ISSUE TITLE
Unable to use a git checkout version of meteor

### ISSUE THREAD

**Issue by olivierpascal** [onmodulus/demeteorizer#130]
Determining Meteor version...
undefined
[Error] Error: Command failed: Unreleased, running from a checkout at ca2c88b (HEAD, origin/devel,
origin/HEAD, devel)

**Comment by fiveisprime** [comment]
This happens because demeteorizer needs to be aware of the Meteor version to
determine how the bundled output is formatted. The line prior to the error that
says `undefined` is the result of running `$ meteor --version`, which is a
little lame.

At this point, it's pretty safe for demeteorizer to assume a version if none is
returned from Meteor.

**Comment by sjmcdowall** [comment]
Not sure this is a helpful idea .. but in the projects .meteor directory there is a "release" file that contains the meteor version in a string like

METEOR@1.1.0.3

Maybe it would be better to look/parse that?
