### ISSUE TITLE
.modulusignore does not work with 'modulus deploy'

### ISSUE THREAD

**Issue by 123ndy** [onmodulus/demeteorizer#162]
I have a lot of static files (images, css, videos, fonts etc) that I don't want to upload to Modulus (I am placing them in a Google bucket). Unfortunately, when I run 'modulus deploy' in the root folder of my Meteor project, it also uploads those static files even though I have put them in my .modulusignore file.

For now, I am manually removing the static files from my project folder every time I am doing a 'modulus deploy', but it would be nice not to have to do this :)

**Comment by jackboberg** [comment]
Thanks for the note. The issue is that `modulus deploy` targets the `.demeteorized` directory, instead of the project root. I think we should add logic to the CLI to copy your `.modulusignore` file into that directory after demeteorizing. I don't think it makes sense to try to add that logic to this project, we should open the issue there.

**Comment by 123ndy** [comment]
Thanks for fast reply @jackboberg
