### ISSUE TITLE
Upgrade Node version

### ISSUE THREAD

**Issue by jbrozena22** [onmodulus/demeteorizer#191]
Meteor 1.3 (the current latest) uses Node 0.10.43. This tool builds with Node 0.10.41

I've been using 1.3 without any obvious ramifications but would prefer it if the build tool brought down the latest for Meteor.

Thanks!

**Comment by harlanj** [comment]
@jbrozena22 a new version of `demeteorizer` was just published and you can set the `node` and `npm` version with flags

`$ demeteorizer --node-version <version> --npm-version <version>`

You can create a PR to update the default node version as well. Let me know if that helps any!

**Comment by jbrozena22** [comment]
Thanks for the response & workaround. 

https://github.com/onmodulus/demeteorizer/blob/master/lib/find-node-version.js#L6

The default node version appears to be 0.10.33, yet when I deploy I get 0.10.41. 

Any idea why / how it determines to use 0.10.41? I ask because I don't want to bump the version number up if there is a reason it's being held at 41.

**Comment by harlanj** [comment]
After looking into a few things, `demeteorizer` checks to see if a node version is specified in `boot.js`. That file is in the same directory as the `package.json` that we use to start your application. I can't be certain of why `demeteorizer` does this, but I would guess that it does because these are the files the Meteor generates. So they would have a reason as to why they put that node version there. You can check it out in [`demeteorizer`](https://github.com/onmodulus/demeteorizer/blob/v3.1.0/lib/find-node-version.js). Also, since `demeteorizer` utilizes the version of Meteor installed, the version used in the build image may have that set in the `boot.js` by default. Updating the version of Meteor used may change this. I'm not 💯 % sure though.

**Comment by harlanj** [comment]
@jbrozena22 with the new update to Meteor, you can now utilize `node@v4`. We're trying to see how `demeteorizer` will account for this, while maintaining backwards compatibility with meteor apps that cannot run on `node@v4`

**Comment by jackboberg** [comment]
Currently using `METEOR@1.4.0.1` and this is causing troubles, it should be `4.x`

```
› meteor create simple-todos
› cd simple-todos
› meteor build --server localhost --directory ./out --server-only
› cat out/bundle/programs/server/boot.js | grep MIN_NODE_VERSION
var MIN_NODE_VERSION = 'v0.10.41';
```

**Comment by sjmcdowall** [comment]
@jackboberg -- I don't think this is a demeteorizer error, and I don't even think it's a meteor issue.  Just because 1.4 CAN use 4.X node, doesn't mean that's the MINIMUM version that can be used.  As far as I know -- and you would need to ask the MDG guys -- Meteor 1.4 apps can still run on 0.10.41 node, so hence the MIN_NODE_VERSION of 0.10.41 makes sense?

**Comment by jackboberg** [comment]
@sjmcdowall makes sense, we are just getting reports from Modulus users that there code requires `4.x` and we can't detect that we should be using it. I think you are right though, the `MIN_NODE_VERSION` is not `4.x`, unless you are using features that require it 😥

**Comment by sjmcdowall** [comment]
@jackboberg I haven't looked into 1.4 yet, but I presume there isn't an easy way to specify the MIN_NODE_VERSSION you want on the command line that could be passed to demeteorizer?

**Comment by jackboberg** [comment]
`demeteorizer` already supports [passing a node version](https://github.com/onmodulus/demeteorizer/blob/master/lib/find-node-version.js#L14). I guess the problem is that we need users of the Modulus CLI to be able to express intent to use `4.x`, and have our build servers pick that up and pass it to `demeteorizer`..

**Comment by theworkflow** [comment]
The Modulus CLI has the ability to pass the node version to the build image for `demeteorizer` to utilize. If this is still an issue please feel free to comment and reopen @jbrozena22
